# # # # # # # # # # # # # # # # # # # # # # # # # #
#   ________                     __    ____  ___  #
#  /  _____/___________    _____/  |_  \   \/  /  #
# /   \  __\_  __ \__  \  /    \   __\  \     /   #
# \    \_\  \  | \// __ \|   |  \  |    /     \   #
#  \______  /__|  (____  /___|  /__|   /___/\  \  #
#         \/           \/     \/             \_/  #
# # # # # # # # # # # # # # # # # # # # # # # # # #
# |
# ---------------------------------------------------------------------------------------
# Welcome to the official settings file for GrantX!
# This is where you can change how GrantX functions.
# If you are unsure of what something does: https://demeng.dev/grantx/docs
# Stuck? Getting errors? Contact out support team at https://demeng.dev/discord.
# Thank you for using GrantX!
# ---------------------------------------------------------------------------------------

config-version: 6

# Your license key, required to activate GrantX.
# Go to https://demeng.dev/discord and create a ticket to obtain one.
# IF YOU DOWNLOADED FROM SPIGOT, IGNORE. This is already automatically done internally.
license-key: "NONE"

# The list of commands that will be executed on rank/permission grant, expiry, and revocation.
# Not reloaded during /grantx reload.
# Do not include the / sign in front of the command.
# Dependent on your permissions plugin. NOTHING WILL HAPPEN on these events if your commands are incorrect!
# You can use the following placeholders. Use common sense when using these.
# Example: Some things like %next-best-group% won't work for permission grants.
# %id% - The ID of the grant.
# %time% - The date of when the grant was issued.
# %target% - The username of the player receiving the grant.
# %target-uuid% - The UUID of the player receiving the grant.
# %staff% - The username of the staff member granting the grant.
# %staff-uuid% - The UUID of the staff member granting the grant.
# %type% - The type of the grant, Rank or Permission.
# %rank% - The name of the rank or permission.
# %real% - The group name of the rank or the permission node of the permission.
# %duration% - The duration of the grant, in words.
# %seconds% - The duration of the grant, in seconds.
# %expiry% - The date and time of grant expiry.
# %reason% - The reason for the grant.
# %next-best-group% - The next best rank's group name after the current one.
# %revoker% - The name of the staff who revoked the grant.
# %revoker-uuid% - The UUID of the staff who revoked the grant.
commands-executed-on:
  rank:
    grant:
      - "Not Set"
    expiry:
      - "Not Set"
    revoke:
      - "Not Set"
  permission:
    grant:
      - "Not Set"
    expiry:
      - "Not Set"
    revoke:
      - "Not Set"

# If GrantX should check for updates and new releases.
check-for-updates: true

# The number of TICKS between every grant expiry check.
# Not reloaded during /grantx reload.
# Assume 20 ticks = 1 second.
# Setting this to a low number will result in more accurate expiration times, but will be more resource-intensive.
# Generally no one really cares if their 5 minute rank is 5 minutes and 10 seconds, which is why 200 is the default.
# You may want to lower this if you often "troll" players and want to give 2 second ranks, etc.
expiry-check-interval: 200

# The default rank on join and the fallback rank when %next-best-group% is requested but there isn't one.
# This must be an actual rank, not a permission.
default-grant:
  # Should this feature be enabled?
  enabled: false
  # The identifier of the rank in ranks.yml.
  rank: "Member"
  # The identifier of the duration in durations.yml.
  duration: "permanent"
  # The identifier of the reason of the grant in reasons.yml.
  reason: "Default Grant"

# List of player UUID's that cannot be interacted with.
# All users listed here cannot be granted and cannot have their grant history viewed.
protected-users:
  - "ca19af04-a156-482e-a35d-3f5f434975b5"

# How the messages logged in the grant log files should be formatted.
# You can use the following placeholders. Use common sense when using these.
# Example: Some things like %next-best-group% won't work for permission grants.
# %id% - The ID of the grant.
# %time% - The date of when the grant was issued.
# %target% - The username of the player receiving the grant.
# %target-uuid% - The UUID of the player receiving the grant.
# %staff% - The username of the staff member granting the grant.
# %staff-uuid% - The UUID of the staff member granting the grant.
# %type% - The type of the grant, Rank or Permission.
# %rank% - The name of the rank or permission.
# %real% - The group name of the rank or the permission node of the permission.
# %duration% - The duration of the grant, in words.
# %seconds% - The duration of the grant, in seconds.
# %expiry% - The date and time of grant expiry.
# %reason% - The reason for the grant.
# %next-best-group% - The next best rank's group name after the current one.
# %revoker% - The name of the staff who revoked the grant.
# %revoker-uuid% - The UUID of the staff who revoked the grant.
log-format:
  # The format when a new grant is issued.
  grant: "Player %target% was granted the %rank% rank for a period of %duration% for the reason %reason% by staff member %staff%."
  # The format when a grant expires by time.
  expiry: "Player %target%'s %rank% rank grant for the reason %reason% by staff member %staff% has expired after a period of %duration%."
  # The format when a grant has been manually revoked by a staff member.
  revoke: "Player %target%'s %rank% rank grant for a period of %duration% for the reason %reason% by staff member %staff% was revoked by staff member %revoker%."

# Should placeholders' colors be stripped (reset)?
strip-placeholder-colors:
  # For %rank% placeholder.
  ranks: true
  # For %duration% placeholder.
  durations: true
  # For %reason% placeholder.
  reasons: true
